### ISSUE TITLE
divider in form generates <h3></h3> before <hr>

### ISSUE THREAD

**Issue by neckarpixel** [stefansl/divider#1]
Hey,
if I'm insert a divider in the form generator, the widget is generating a `h3></h3>` before the `<hr>` element

`<div class="ce_form first last tableless block"> <form action="kontakt" id="f2" method="post" enctype="application/x-www-form-urlencoded"><div class="formbody"> <input type="hidden" name="FORM_SUBMIT" value="auto_form_2"> <input type="hidden" name="REQUEST_TOKEN" value="31df871058410f6aaedd11f8bef9e0f2"> <h3></h3><hr></div></form></div>`

<img width="743" alt="bildschirmfoto 2016-10-20 um 09 22 54" src="https://cloud.githubusercontent.com/assets/130322/19550005/9c8e46ae-96a7-11e6-9ef8-9185b578015b.png">

I've disabled all 3rd party extentions but there is no effect in rendering the form widget also.

Any idea?

Contao 3.5.17
stefansl/divider 1.2.4

**Comment by neckarpixel** [comment]
I think you have to use an own template instead of `be_widget` because there will always generated a `<h3>`

be_widget.html5

`<h3><?= $this->generateLabel() . $this->xlabel ?></h3>
<?= $this->generateWithError(true) ?>`

**Comment by stefansl** [comment]
thx! i will check it soon. 👍

**Comment by stefansl** [comment]
I added a new version with some more improvements. See https://github.com/stefansl/divider/releases/tag/1.3.0

**Comment by neckarpixel** [comment]
Woohoo!! thx!!
